export const FIXED_EXPENSE_CATEGORIES = [
  'Loyer',
  'Remboursement prêt maison',
  'Remboursement prêt voiture',
  'Telus Streaming',
  'Netflix',
  'Disney+',
  'Amazon Prime',
  'Spotify',
  'Téléphone(s)',
  'YouTube Premium',
  'Électricité',
  'Eau',
  'Assurance logement',
  'Assurance voiture',
  'Faceit Premium',
  'Claude',
  'ChatGPT',
  'Autre',
];

export const ALLOCATION_CATEGORIES = [
  'CELI',
  'Livret A',
  'Bourse',
  'Assurance santé privée',
  'Una',
  "Fonds d'urgence",
  'Courses',
  'Essence',
  'Sorties',
  'Beauté',
  'Autre',
];

export const CHART_COLORS = [
  '#6c63ff',
  '#ff6584',
  '#43d9ad',
  '#ffd166',
  '#06d6a0',
  '#ef476f',
  '#118ab2',
  '#ffd60a',
  '#9d4edd',
  '#f77f00',
  '#4cc9f0',
  '#7209b7',
  '#3a0ca3',
  '#4361ee',
  '#4895ef',
  '#560bad',
  '#b5179e',
  '#f72585',
];
